version: '3'

services:
  docs:
   image: dtr.rogfk.no/fint-beta/information-model-documentation-portal
   ports:
     - "9003:3000"
   environment:
    TZ: Europe/Oslo
    GITHUB_ORGANISATION: "FINTprosjektet"
    GITHUB_REPO: "FINT-informasjonsmodell-metamodell"
    EA_XMI_FILENAME: "FINT-metamodell.xml"
   deploy:
    replicas: 3
    restart_policy:
     condition: on-failure
     delay: 5s
     max_attempts: 3
     window: 120s
