version: '3'

services:
  docs:
   image: fint/documentation-portal
   ports:
     - "9001:3000"
   environment:
    TZ: Europe/Oslo
   deploy:
    replicas: 1
    restart_policy:
     condition: on-failure
     delay: 5s
     max_attempts: 3
     window: 120s
