version: '2'

services:
  documentation:
    build: .
    image: fint/informasjonsmodell-documentation
    container_name: fint-informasjonsmodell-documentation
    restart: unless-stopped
    ports:
      - "8092:3000"
    volumes:
      - /usr/src/app/node_modules
