version: '2'

services:
  documentation:
    build: .
    image: fint/informasjonsmodell-documentation
    container_name: ${DOCKER_CONTAINER}
    restart: unless-stopped
    ports:
      - "${DOCKER_PORT}:3000"
    volumes:
      - /usr/src/app/node_modules
