apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: informasjonsmodell-documentation
  name: informasjonsmodell-documentation
spec:
  ports:
    - name: "3000"
      port: 3000
    - name: "3001"
      port: 3001
  type: LoadBalancer
  selector:
    io.kompose.service: informasjonsmodell-documentation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: informasjonsmodell-documentation
  name: informasjonsmodell-documentation
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      io.kompose.service: informasjonsmodell-documentation
  template:
    metadata:
      labels:
        io.kompose.service: informasjonsmodell-documentation
    spec:
      containers:
        - name: informasjonsmodell-documentation
          image: fintlabsacr.azurecr.io/fint-informasjonsmodell-documentation:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 5
            httpGet:
              port: 3000
              path: /health
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
            requests:
              memory: "2Gi"
              cpu: "1"
          env:
            - name: TZ
              value: Europe/Oslo
            - name: GITHUB_ORGANISATION
              value: FINTLabs
        - name: informasjonsmodell-documentation-metamodell
          image: fintlabsacr.azurecr.io/information-model-documentation-portal:meta.3
          ports:
            - containerPort: 3001
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 5
            httpGet:
              port: 3001
              path: /health
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: TZ
              value: Europe/Oslo
            - name: GITHUB_ORGANISATION
              value: FINTLabs
            - name: GITHUB_REPO
              value: FINT-informasjonsmodell-metamodell
            - name: EA_XMI_FILENAME
              value: FINT-metamodell.xml
            - name: PORT
              value: "3001"
