apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: informasjonsmodell-documentation
  name: informasjonsmodell-documentation
spec:
  ports:
    - name: "3000"
      port: 3000
    - name: "3001"
      port: 3001
  type: LoadBalancer
  selector:
    io.kompose.service: informasjonsmodell-documentation
