name: CD

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:

  build-push:
    uses: fintlabs/shared-workflows/.github/workflows/docker-build-push.yaml@main
    secrets: inherit

  beta:
    needs: build-push
    uses: fintlabs/shared-workflows/.github/workflows/java-kustomize-deploy.yaml@main
    with:
      tags: ${{ needs.build-push.outputs.tags }}
      environment: beta
      deploy-every-branch: true
    secrets: inherit

  prod:
    needs: [ build-push, beta ]
    uses: fintlabs/shared-workflows/.github/workflows/java-kustomize-deploy.yaml@main
    with:
      tags: ${{ needs.build-push.outputs.tags }}
      environment: api
    secrets: inherit

